# -*- coding: utf-8 -*-
"""data_process.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBuQRHIte_K1oSZ2TbgaxfWkD9IyDFRz
"""

import numpy as np
import pandas as pd

def scores_to_target(train_scores):
  target = np.zeros(len(train_scores))
  target += -1 * train_scores.loc[:,'AWAY_WINS'].values
  target += train_scores.loc[:, 'HOME_WINS'].values
  return target