# -*- coding: utf-8 -*-
"""clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WoR2_IAAC8PWWthBFXe8Jsoslm2cWzYR
"""

from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

def kmeans_clustering(train_data, n_clusters = 4, fill_init_median = True, normalize = True):
  if(fill_init_median):
    train_data_copy = train_data.fillna(train_data.median()).copy()
  else:
    train_data_copy = train_data.fillna(train_data.mean()).copy()
  if(normalize):
    scaler = MinMaxScaler()
    train_data_copy = scaler.fit_transform(train_data_copy)
  kmeans = KMeans(n_clusters=n_clusters, random_state=0).fit(train_data_copy)
  train_data['cluster'] = kmeans.labels_
  return train_data