# -*- coding: utf-8 -*-
"""get_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0Am-s4ekBuO6p9QJ7njNYQ_-3CFMLvV
"""

import pandas as pd
import numpy as np
import os
import sys
from google.colab import drive
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler
from clustering_methods import kmeans_clustering
